{% set name = "paho-mqtt" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12d6e7511d4137555a3f6ea167ae846af2c7357b10bc6fa4f7c3968fc1723834

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install --old-and-unmanageable

requirements:
  host:
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}

test:
  imports:
    - paho
    - paho.mqtt
    - paho.mqtt.client
  requires:
    - python {{ python_min }}

about:
  home: http://eclipse.org/paho
  license: EPL-2.0 AND BSD-3-Clause
  license_family: OTHER
  license_file: LICENSE.txt
  summary: MQTT version 3.1.1 client class
  description: Eclipse Paho MQTT Python Client

extra:
  recipe-maintainers:
    - ilanschnell
    - nerohmot
