{% set name = "paho-mqtt" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 13b205f29251e4f2c66a6c923c31fc4fd780561e03b2d775cff8e4f2915cf947

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install --old-and-unmanageable

requirements:
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - paho
    - paho.mqtt
  requires:
    - mock
    - pylama
    - pytest
    - six

about:
  home: http://eclipse.org/paho
  license: EPL-2.0 AND BSD-3-Clause
  license_family: OTHER
  license_file: LICENSE.txt
  summary: MQTT version 3.1.1 client class
  description: Eclipse Paho MQTT Python Client

extra:
  recipe-maintainers:
    - ilanschnell
    - nerohmot
